version: 2.1
orbs:
  node: circleci/node@5.1.0

parameters:
  rerun-failed:
    type: boolean
    default: false

jobs:
  build-and-test:
    parallelism: 4
    resource_class: small
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: | 
              mkdir test-results
              #  TEST_FILES=$(circleci tests glob "**/test_*.py")
              #  pytest -o junit_family=legacy --junitxml=test-results/junit.xml $TEST_FILES
              echo "up next are the tests i received:"
              pytest --collect-only -q | grep -e "\.py" | circleci tests run --command="xargs" \
              --verbose \
      - run:
          name: test_it
          command: pytest -o junit_family=legacy --junitxml=test-results/junit.xml
      - store_test_results:
            path: test-results

  build:
    executor: node/default # use the default executor specified by the orb
    steps:
      - checkout
      - node/install-packages # Use a command from the orb in a job's steps
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: jest --help


  step-example:
    resource_class: small
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          command: echo "this is a clickable link https://circleci.com"
          
workflows:
  sample:
    jobs:
      #- build-and-test
      #- node/run
      - step-example